#!/usr/bin/env bash

# Description ->
#
# |- Summary: Flatpak aliases and functions (cross-distro)
#             - Flatpak package management
#             - FZF package search (flatf)
#
# |- Dependencies:
#             - flatpak
#             - fzf

# Document Info ->
#
# |- Author: RilCritch
#
# |- Last Update: 02/14/2026


# Aliases {{{

alias flls='flatpak list --app --columns=name,application,version'
alias flla='flatpak list'
alias flup='flatpak update'

# }}}


# FZF Package Functions {{{

flatf() {
    local choice

	choice=$(flatpak remote-ls flathub | awk '{ printf "%s %s\n", $1, $2, $3 }' | fzf --header-first --reverse --prompt='▶ ' --pointer='󱦰' --preview $'flatpak remote-info flathub "$(echo {} | awk \'{printf "%s", $2}\')"')

	if [ -n "$choice" ]; then
		echo "Installing $choice" | clr green
		# flatpak install flathub "${choice}"
	fi
}

# }}}


# Vim options - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# vim: ts=4 sts=4 sw=4 et
# vim:fileencoding=utf-8:foldmethod=marker
