#!/usr/bin/env bash

# Description ->
#
# |- Summary: Directory listing functions using eza
#             - Recursive, tree, and in-depth listing outputs
#
# |- Dependencies:
#             - eza
#             - fdfind
#             - utilities module (get-dir-c, is_number, tree-size)
#             - ansi_escape_sequences

# Document Info ->
#
# |- Author: RilCritch
#
# |- Last Update: 02/14/2026


# Recursive {{{

lsr() {
	local size="$1"

	# Default size of 2
	if [ -z "$size" ] || [ "$size" -le 0 ]; then
		size=2
	fi

	eza -R --icons -L="$size" --group-directories-first
}

lsra() {
	local size="$1"

	# Default size of 2
	if [ -z "$size" ] || [ "$size" -le 0 ]; then
		size=2
	fi

	eza -R -a --icons -L="$size" --group-directories-first
}

clsr() {
	local size="$1"

	# Default size of 2
	if [ -z "$size" ] || [ "$size" -le 0 ]; then
		size=2
	fi

	clear
	eza -R --icons -L="$size" --group-directories-first
}

clsra() {
	local size="$1"
    local ignore="$2" # format "ignore1|ignore2|ignoreN"

	# Default size of 2
	if [ -z "$size" ] || [ "$size" -le 0 ]; then
		size=2
	fi

    # files to ignore
    if [ -z "$ignore" ]; then
        ignore=""
    else
        ignore="--ignore-glob='${2}'"
    fi

	clear
	eval eza -Ra --icons "$ignore" -L="$size" --group-directories-first
}

# }}}


# Tree {{{

lst() {
	local size="$1"

	# Default size of 2
	if [ -z "$size" ] || [ "$size" -le 0 ]; then
		size=2
	fi

	eza -T --icons -L="$size" --group-directories-first
}

clst() {
	local size="$1"

	# Default size of 2
	if [ -z "$size" ] || [ "$size" -le 0 ]; then
		size=2
	fi

	clear
	eza -T --icons -L="$size" --group-directories-first
}

clsta() {
	local size="$1"

	# Default size of 2
	if [ -z "$size" ] || [ "$size" -le 0 ]; then
		size=2
	fi

	clear
	eza -Ta --icons -L="$size" --group-directories-first
}

# }}}


# In Depth List Outputs {{{

# Directory overview
# |- Arg 1: Directory to list (must be valid dir, default: pwd)
# |- Arg 2: Integer specifying extra lines for eza height calculation
dir-overview() {
    # Arguments
    local dir_name
    local extra_lines
    local input
    local dir_path
    local num_files
    local num_dirs
    local num_links
    local tree_height
    local dir_length
    local files_length
    local dirs_length
    local links_length
    local linewidth

    dir_name=$(get-dir-c "$1")
    if [[ -z "$dir_name" ]]; then
        echo -e "${red}ERROR: ${reset}Specified Directory ${blue}${1} ${reset}does not exist."
        return 2
    fi

    if [[ -n "${2}" && $(is_number "${2}") -eq 0 ]]; then
        input="${2}"
        extra_lines=$((input + 4))
    else
        extra_lines="4"
    fi

    # Data
    dir_path=$(realpath "${dir_name}")
    num_files=$(fdfind . "${dir_path}" -H --type f --max-depth 1 | wc -l)
    num_dirs=$(fdfind . "${dir_path}" -H --type d --max-depth 1 | wc -l)
    num_links=$(fdfind . "${dir_path}" -H --type l --max-depth 1 | wc -l)
    tree_height=$(tree-size "${dir_path}" "${extra_lines}")

    # output
    if [[ "$tree_height" -eq 0 ]]; then
        echo -en "${cyan} "
        echo -en "${bold}${dir_path}${reset} ${l_black}|"

        echo -en "${reset}  "
        echo -en "${dim} ${num_files}${reset} ${l_black}|"

        echo -en "${blue}  "
        echo -en "${dim} ${num_dirs}${reset} ${l_black}|"

        echo -en "${cyan}  "
        echo -e "${dim} ${num_links}"

        across-line | clr blackL

        eza -a --group-directories-first -I=".git" "$dir_path"
    else
        echo -en "${cyan}  "
        echo -en "${bold}${dir_path}${reset} ${l_black}|"

        echo -en "${reset}  "
        echo -en "${dim} ${num_files}${reset} ${l_black}|"

        echo -en "${blue}  "
        echo -en "${dim} ${num_dirs}${reset} ${l_black}|"

        echo -en "${cyan}  "
        echo -e "${dim} ${num_links}"

        dir_length=${#dir_path}
        files_length=${#num_files}
        dirs_length=${#num_dirs}
        links_length=${#num_links}

        linewidth=$((dir_length + files_length + dirs_length + links_length + 21))

        echo -e -n "${l_black}┍"
        for (( i=1 ; i<=linewidth; i++ )); do
            echo -n "━"
        done
        echo
	    eza -Ta -L="$tree_height" --group-directories-first -I=".git" "$dir_path" | awk 'NR > 1'
    fi
}

# }}}


# Vim options - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# vim: ts=4 sts=4 sw=4 et
# vim:fileencoding=utf-8:foldmethod=marker
