#!/usr/bin/env bash

# Description ->
#
# |- Summary: FZF-powered directory navigation functions
#             - Fuzzy find and traverse directories interactively
#
# |- Dependencies:
#             - fzf
#             - fdfind
#             - eza
#             - utilities module (get-dir-h)
#             - ansi_escape_sequences

# Document Info ->
#
# |- Author: RilCritch
#
# |- Last Update: 02/14/2026


# FZF cd {{{

dir-nav-fzf() {
    # Test for specified dir
    local dir_name
    local dir_path
    local choice

    dir_name=$(get-dir-h "$1")
    if [[ -z "$dir_name" ]]; then
        echo -e "Specified Directory ${blue}${1}${reset} does not exist."
    fi

    dir_path=$(realpath "${dir_name}")

	choice=$(fdfind . "$dir_path" --type d | sed "s|${dir_path}/||" | fzf --border-label=" 󰥨 ${dir_path}/ " --preview "eza --tree -la --icons -F -L=2 --group-directories-first --no-filesize --no-user --no-time --no-permissions {}")

	if [[ -n "$choice" ]]; then
		cd "${dir_path}/${choice}" || return 2
		clear
	fi
}

dir-nav-fzf-hid() {
    # Test for specified dir
    local dir_name
    local dir_path
    local choice

    dir_name=$(get-dir-h "$1")
    if [[ -z "$dir_name" ]]; then
        echo -e "Specified Directory ${blue}${1}${reset} does not exist."
    fi

    dir_path=$(realpath "${dir_name}")

	choice=$(fdfind . "$dir_path" -H --type d | sed "s|${dir_path}/||" | fzf --border-label=" 󰥨 ${dir_path}/ " --preview "eza --tree -la --icons -F -L=2 --group-directories-first --no-filesize --no-user --no-time --no-permissions {}")

	if [[ -n "$choice" ]]; then
		cd "${dir_path}/${choice}" || return 2
		clear
	fi
}

d () {
    # Test for directory path -> default to home
    local dir_name
    local dir_path
    local choice
    local dir_traversal
    local dir_number
    local repo_path
    local header_size
    local extra_lines

    dir_name=$(get-dir-h "$1")
    if [[ -z "${dir_name}" ]]; then
        echo -e "Specified Directory ${blue}${1}${reset} does not exist."
        echo "false"
        return 2
    fi
    dir_path=$(realpath "${dir_name}")

    choice="notempty"
    dir_traversal="false"

    # Run fzf to traverse directories
    while [[ -n "${choice}" ]]; do
        choice=$(fdfind . "$dir_path" -H --type d | sed "s|${dir_path}/||" | fzf --border-label=" 󰥨 ${dir_path}/ " --preview "eza --tree -l --icons -F -L=2 --group-directories-first --no-filesize --no-user --no-time --no-permissions ${dir_path}/{}")

        if [[ -n "${choice}" ]]; then
            dir_traversal="true"

            cd "${dir_path}/${choice}" || return 2

            dir_path=$(realpath "${dir_path}/${choice}")
            dir_number=$(fdfind . "${dir_path}" --type d --max-depth 1 | wc -l)

            # stop loop if ther are no more directories to traverse
            if [[ "${dir_number}" -le 0 ]]; then
                choice=""
            fi
        fi
    done

    # Print data if neccessary
    if [[ "${dir_traversal}" == "true" ]]; then
        clear

        # Git repo?
        repo_path=$(git rev-parse --show-toplevel 2> /dev/null)

        # account for extra height of script output
        if [[ -n "${repo_path}" ]]; then
            repo-header

            header_size=$(repo-header | wc -l)
            extra_lines=$((header_size + 1))
        else
            extra_lines=1
        fi

            dir-overview . "${extra_lines}"
            echo
    fi
}

# Fast cd to my repos
# r() {
# 	choice=$(\ls /home/rc/Repos/ | fzf --height=100% --header-first --border-label="  Git Repositories " --reverse --preview "eza --tree -l --icons -F -L=2 --group-directories-first --no-filesize --no-user --no-time --no-permissions ${HOME}/Repos/{}")
#
#     if [ -n "$choice" ]; then
#         base_dir="/home/rc/Repos/${choice}"
#         cd "${base_dir}" || return 2
#         clear
#
#         dir_number=$(fdfind . "${base_dir}" --type d --max-depth 1 | wc -l)
#         if [[ "$dir_number" -gt 0 ]]; then
#             dir-nav-fzf "${base_dir}"
#         fi
#
#         repo-header
#
#         header_size=$(repo-header | wc -l)
#         extra_lines=$((header_size + 1))
#
#         dir-overview . "${extra_lines}"
#         echo
#     fi
# }

# Fast cd through notes
n() {
    local choice

	choice=$( fdfind . "$HOME/Repos/notes-ril" --type d | sed "s|$HOME/Repos/notes-ril/||" | fzf --border-label=" 󰠮 Search Notes Directory " --header-first --reverse  --preview "eza --tree -la --icons -F -L=2 --group-directories-first --no-filesize --no-user --no-permissions --no-time ${HOME}/Repos/notes-ril/{}")

    if [ -n "$choice" ]; then
        cd "${HOME}/Repos/notes-ril/${choice}" || return 2
        clear

        dir-overview
    fi
}

# }}}


# Vim options - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# vim: ts=4 sts=4 sw=4 et
# vim:fileencoding=utf-8:foldmethod=marker
