#!/usr/bin/env bash

# Description ->
#
# |- Summary: General directory navigation functions
#
# |- Dependencies:
#             - none

# Document Info ->
#
# |- Author: RilCritch
#
# |- Last Update: 02/14/2026


# Navigation {{{

# Moving up directories
up() {
	local d=""
	local limit="$1"

	# Default to limit of 1
	if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
		limit=1
	fi

	for ((i = 1; i <= limit; i++)); do
		d="../$d"
	done

	# perform cd. Show error if cd fails
	if ! cd "$d"; then
		echo "Couldn't go up $limit dirs."
	fi
}

# }}}


# Vim options - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# vim: ts=4 sts=4 sw=4 et
# vim:fileencoding=utf-8:foldmethod=marker
