#!/usr/bin/env bash

# |- Description ->
#    - File that sources autocompletions files

# |- Directories
BASH_COMP="${HOME}/.local/share/bash-completion"
BUILD_DIR="${HOME}/Builds"

# |- Source bash completions ->

[[ -f /usr/share/bash-completion/bash_completion ]] && \
    . /usr/share/bash-completion/bash_completion

[[ -f "${BASH_COMP}/gita-completion.bash" ]] && . "${BASH_COMP}/gita-completion.bash"
[[ -f "${HOME}/Builds/qmk_firmware/util/qmk_tab_complete.sh" ]] && . "${HOME}/Builds/qmk_firmware/util/qmk_tab_complete.sh"
[[ -f "${BASH_COMP}/girok.sh" ]] && . "${BASH_COMP}/girok.sh"

[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# |- FZF completion engine ->

# [[ -f "${BUILD_DIR}/fzf-tab-completion/bash/fzf-bash-completion.sh" ]] &&
#     source "${BUILD_DIR}/fzf-tab-completion/bash/fzf-bash-completion.sh"
# bind -x '"\t": fzf_bash_completion'

# Vim options ->
# vim:fileencoding=utf-8:foldmethod=marker
