#!/usr/bin/bash

# vim:fileencoding=utf-8:foldmethod=marker

# environment variables for bashrc
#
# author: RilCritch

## directories {{{

export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export MOST_INITFILE="$HOME/.config/most/most.rc"

# }}}

## mis applications {{{

export EZA_ICON_SPACING=1
export STARSHIP_LOG="error"

# }}}
#
## FZF {{{

export FZF_DEFAULT_OPTS="--header-first --reverse \
--no-scrollbar --border --height=~50% \
--prompt=' ' --pointer='▶' --marker='󱦰' \
--color='fg:0,fg+:7,bg:-1,bg+:-1,\
hl:-1,hl+:6,info:15,border:8,header:4,\
prompt:6,pointer:4,spinner:3'"

#}}}

## window managers {{{

# qtile

# }}}

## programming {{{

# python
export WORKON_HOME="$HOME/documents/programming/pyenvs"

# }}}
