#!/usr/bin/bash

# vim:fileencoding=utf-8:foldmethod=marker

# environment variables for bashrc
#
# author: RilCritch

## RilCritch's Environment {{{


# Directories
export RCS_DIR="${HOME}/.local/share/rc-scripts" #: RC Scripts data location
export RCS_BIN_DIR="${HOME}/.local/bin"
export BASH_HOME="${HOME}/Repos/bash-ril"

# User info
export RCS_NAME="RilCritch" #: preferred name

# Git info
export RCS_GIT_USERNAME="${RCS_NAME}"

# }}}

## directories {{{

export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export MOST_INITFILE="$HOME/.config/most/most.rc"

# }}}

## mis applications {{{

export EZA_ICON_SPACING=1
export STARSHIP_LOG="error"
export EDITOR="nvim"

# }}}

## Gimp {{{

export GIMP2_DIRECTORY="${HOME}/.config/GIMP/2.10"

# }}}

## FZF {{{

export FZF_DEFAULT_COMMAND="fdfind"

export FZF_DEFAULT_OPTS="--header-first \
--reverse --border-label-pos=2 \
--no-scrollbar --border --height=~50% \
--scheme='history' --history-size=2000 \
--history='${HOME}/Repos/notes-ril/software_history/fzf_hist' \
--prompt='󰍉 ' --pointer='' --marker='󰮺' \
--color='\
fg:black,fg+:-1,preview-fg:white,\
bg:-1,bg+:-1,preview-bg:-1,\
hl:cyan:dim,hl+:blue:underline,\
query:cyan,disabled:cyan:dim,\
prompt:cyan:dim,pointer:blue,marker:blue:dim,\
info:bright-white,spinner:yellow,\
border:white,separator:bright-black:dim,scrollbar:8:dim,\
header:cyan,label:blue:bold,preview-label:cyan'"

#}}}

## window managers {{{

# qtile

# }}}

## programming {{{

# python
export WORKON_HOME="$HOME/documents/programming/pyenvs"

# }}}

## tasks {{{

# NOTE: these are a work on progress
# Defaults:
# TSK_DIR="${XDG_DATA_HOME}/tasks_storage"
# TSK_DEF_CAT="General"
# TSK_EDITOR="\nano"
# TSK_VIEWER="\cat"
# TSK_NAVIGATION="cli"

# Testing:
# TSK_DIR="/home/rc/Documents/Testing/tasks_script/code/testing_dir"
# TSK_DEF_CAT="General"
# TSK_EDITOR="\nvim"
# TSK_VIEWER="\glow"
# TSK_NAVIGATION="fzf"

#}}}
