#!/usr/bin/env bash

# Description ->
#
# |- Summary: Shell options and keybindings for bash
#             - shopt settings, completion behavior
#
# |- Dependencies:
#             - none

# Document Info ->
#
# |- Author: RilCritch
#
# |- Last Update: 02/14/2026

# |- Options ->

#ignore upper and lowercase when TAB completion
bind "set completion-ignore-case on"

#shopt
shopt -s autocd  # change to named directory
shopt -s cdspell # autocorrects cd misspellings
shopt -s cmdhist # save multi-line commands in history as single line
shopt -s dotglob
shopt -s histappend     # do not overwrite history
shopt -s expand_aliases # expand aliases

# Vim options ->
# vim:fileencoding=utf-8:foldmethod=marker
