#!/usr/bin/env bash

# Description ->
#
# |- Summary: PATH management for bash environment
#             - Adds directories to PATH using pathadd() helper
#
# |- Dependencies:
#             - none

# Document Info ->
#
# |- Author: RilCritch
#
# |- Last Update: 02/14/2026

# |- Function ->
pathadd() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        export PATH="${PATH:+"$PATH:"}$1"
    fi
}

# |- Adding Paths ->

# General directories
pathadd "${HOME}/.bin"
pathadd "${HOME}/.local/bin"

# Custom directories
pathadd "${HOME}/.local/rilbin"
pathadd "${HOME}/.local/rilbin/color-scripts"
pathadd "${HOME}/.local/rilbin/starship"
pathadd "${HOME}/.local/rilbin/file-management"
pathadd "${HOME}/Documents/testing"
pathadd "${HOME}/Repos/scripts-ril"
pathadd "${HOME}/Repos/scripts-ril/color-scripts"

# Package directories
pathadd "/usr/local/go/bin"
pathadd "${HOME}/.local/share/go/bin"
pathadd "${HOME}/Builds/bat-extras/bin"
pathadd "${HOME}/.local/share/npm/bin"
pathadd "${HOME}/.juliaup/bin"

# Tool Directories
pathadd "${HOME}/.opencode/bin"

# Vim options ->
# vim:fileencoding=utf-8:foldmethod=marker
