#!/usr/bin/env bash

# Functions for startup in bash


# Inital Prompt
startup-actions() {
    # Prompt user with fzf
    options=("Repo Nav" "Dir Nav" "Packages" "Man Pages" "Calendar")
    action=$(printf '%s\n' "${options[@]}" | fzf --header-first --height=100% --reverse --prompt=' ' --pointer='󰮺' --header="Startup Options")

    # Check users selection
    case "$action" in
    "Repo Nav") # Navigate through repositories
        repo-nav
        ;;
    "Dir Nav") # Navigate through all directories in user home
        d
        ;;
    "Packages") # Search for packages to install
        ddf
        ;;
    "Man Pages") # Search for man pages
        man
        ;;
    "Calendar") # Manage calendar and planning
        calcure
        ;;
    *) # No option action - startup in home dir
        echo "default"
        ;;
    esac
}

# Repo navigation
repo-nav() {
	choice=$(\ls /home/rc/Repos/ | fzf --header-first --reverse --prompt='▶ ' --pointer='󱦰' --preview "eza --tree -la --icons -F -L=2 --group-directories-first --no-permissions --no-filesize --no-user --no-time -I='.git' /home/rc/Repos/{}")

    if [ -n "$choice" ]; then
        cd "${repo_name}"
        clear

        # sparky | clr blackL
        # lsa
        # lineacross | clr blackL
        # git status -s
        # git summary
    fi
}
