#!/usr/bin/env bash

# Description ->
#
# |- Summary:
#             - File for testing ideas for bashrc
#
# |- Usage: Place functions or other bash script to be sourced in bashrc
#

# Document Info ->
#
# |- Author: Riley Crtichfield
#
# |- Last Update: 02/10/2024


# |- Functions ->

## Testing New Functions {{{

# Testing Directory Access
# dir-test() {
#     if [[ -z "$1" ]]; then
#         dir="${HOME}"
#         echo "Dir set to default -> \$dir=${dir}"
#     else
#         if [[ -d "$1" ]]; then
#             dir="$1"
#             echo "Dir set to argument -> \$dir=${dir}"
#         else
#             echo "Dir not set as specified dir does not exist"
#             return 1
#         fi
#     fi
#     echo "end of function"
# }

# }}}

## Old and currently not in use {{{

# fast cd on root - verbose and clear screen
# dr() {
# 	sudo -v
# 	choice=$(sudo fdfind . / -type d | fzf --header-first --reverse --prompt='▶ ' --pointer='󱦰' --preview 'eza --tree -la --icons -F -L=2 --group-directories-first --no-filesize --no-user --no-time --no-permissions {}')
#
# 	if [ -n "$choice" ]; then
# 		cd $choice
# 		clear
#
# 		# sparky | clr blackL
#         echo -e "${black}-| ${cyan}${bold}$(\pwd)${reset}${black} |-${reset}"
# 		# eza -la --group-directories-first --icons --grid --no-user --no-filesize
#         lsa
# 		lineacross | clr blackL
# 	fi
# }

# fzf through different neovim configs
# need to set up for my new debian envioronment
# snv() {
# 	# items=("default" "from-scratch" "lazy-nvim" "nv-chad" )
#     items=$(\ls ~/.config/neovim/)
# 	config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config   " --exit-0)
# 	if [[ -z $config ]]; then
# 		# echo "Nothing selected"
# 		return 0
#     else
#         config="neovim/${config}"
# 	fi
# 	NVIM_APPNAME=$config nvim "$@"
# }

# show the list of packages that need this package - depends mpv as example
# depends() {
# 	search=$(echo "$1")
# 	sudo pacman -Sii $search | grep "Required" | sed -e "s/Required By     : //g" | sed -e "s/  /\n/g"
# }

# }}}

# |- Aliases ->

##  TODO: Place shell here


# |- Misc ->

# Vim options - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# vim:fileencoding=utf-8:foldmethod=marker
